# Generated by Django 5.1.5 on 2025-02-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
                ('location_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
