# Generated by Django 4.2.19 on 2025-02-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shopify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='ShopStore',
        ),
    ]
